import streamlit as st
import pandas as pd
from utils.loader import (
    list_experiments,
    load_all_experiments_summary,
    load_overall_metrics,
    load_fold_metrics,
    load_config,
)
from utils.plots import plot_metrics_comparison, plot_fold_bars
from utils.sidebar import render_sidebar

st.set_page_config(
    page_title="EEG Analysis Dashboard",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded",
)

render_sidebar()

st.title("🧠 EEG Multimodal Analysis Dashboard")
st.markdown("#### EEGNet baselines on MODMA dataset — 5-fold cross-validation")

df_summary = load_all_experiments_summary()

if df_summary.empty:
    st.warning("No experiments found. Run a benchmark first.")
    st.stop()

col1, col2, col3, col4 = st.columns(4)

best_acc = df_summary.loc[df_summary["accuracy"].idxmax()] if "accuracy" in df_summary.columns else None
best_f1 = df_summary.loc[df_summary["f1_macro"].idxmax()] if "f1_macro" in df_summary.columns else None

col1.metric("Experiments", len(df_summary))
col2.metric(
    "Best Accuracy",
    f"{best_acc['accuracy']:.2%}" if best_acc is not None else "—",
    delta=f"±{best_acc['accuracy_std']:.2%}" if best_acc is not None else None,
)
col3.metric(
    "Best Balanced Acc",
    f"{best_acc['balanced_accuracy']:.2%}" if best_acc is not None else "—",
    delta=f"±{best_acc['balanced_accuracy_std']:.2%}" if best_acc is not None else None,
)
col4.metric(
    "Best F1-macro",
    f"{best_f1['f1_macro']:.4f}" if best_f1 is not None else "—",
    delta=f"±{best_f1['f1_macro_std']:.4f}" if best_f1 is not None else None,
)

st.markdown("---")

tab_comparison, tab_table = st.tabs(["Comparison Chart", "All Experiments"])

with tab_comparison:
    fig = plot_metrics_comparison(df_summary)
    st.plotly_chart(fig, use_container_width=True)

with tab_table:
    cols = ["experiment", "accuracy", "balanced_accuracy", "f1_macro",
            "model", "duration_sec", "batch_size", "weight_decay", "lr_scheduler"]
    display_cols = [c for c in cols if c in df_summary.columns]
    df_display = df_summary[display_cols].copy()

    for c in ["accuracy", "balanced_accuracy"]:
        if c in df_display.columns:
            df_display[c] = df_display[c].apply(lambda x: f"{x:.2%}" if pd.notna(x) else "—")
    if "f1_macro" in df_display.columns:
        df_display["f1_macro"] = df_display["f1_macro"].apply(
            lambda x: f"{x:.4f}" if pd.notna(x) else "—"
        )

    st.dataframe(
        df_display.sort_values("accuracy" if "accuracy" in df_display.columns else "experiment",
                               ascending=False),
        use_container_width=True,
        hide_index=True,
    )

st.markdown("---")
st.subheader("Per-Experiment Fold Details")

selected_exp = st.selectbox(
    "Select experiment to view fold metrics",
    options=df_summary["experiment"].tolist(),
    index=len(df_summary) - 1,
)

df_folds = load_fold_metrics(selected_exp)

if not df_folds.empty:
    col_left, col_right = st.columns(2)

    with col_left:
        metric_choice = st.selectbox(
            "Metric",
            options=[c for c in df_folds.columns if c not in ("fold", "best_epoch", "n_epochs")],
            index=0,
        )
        fig = plot_fold_bars(df_folds, metric=metric_choice)
        st.plotly_chart(fig, use_container_width=True)

    with col_right:
        st.dataframe(df_folds, use_container_width=True, hide_index=True)

st.caption("Data from `outputs/models/modma_db/` — Generated by benchmark_modma.py")
