from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from utils.loader import load_all_experiments_summary
from utils.plots import plot_metrics_comparison
from utils.sidebar import render_sidebar

st.set_page_config(
    page_title="EEG Analysis Dashboard",
    page_icon="",
    layout="wide",
    initial_sidebar_state="expanded",
)

render_sidebar()

st.title("EEG Analysis Overview")
st.markdown("EEGNet baselines on **MODMA** dataset — 5-fold cross-validation")

ds = st.session_state.get("selected_dataset", "modma_db")
df_summary = load_all_experiments_summary(ds)

if df_summary.empty:
    st.warning("No experiments found. Run a benchmark first.")
    st.stop()

col1, col2, col3, col4 = st.columns(4)

best_acc = (df_summary.loc[df_summary["accuracy"].idxmax(skipna=True)]
            if "accuracy" in df_summary.columns and df_summary["accuracy"].notna().any()
            else None)
best_f1 = (df_summary.loc[df_summary["f1_macro"].idxmax(skipna=True)]
           if "f1_macro" in df_summary.columns and df_summary["f1_macro"].notna().any()
           else None)

col1.metric("Experiments", len(df_summary))
col2.metric(
    "Best Accuracy",
    f"{best_acc['accuracy']:.2%}" if best_acc is not None else "—",
    delta=f"±{best_acc['accuracy_std']:.2%}" if best_acc is not None else None,
)
col3.metric(
    "Best Balanced Acc",
    f"{best_acc['balanced_accuracy']:.2%}" if best_acc is not None else "—",
    delta=f"±{best_acc['balanced_accuracy_std']:.2%}" if best_acc is not None else None,
)
col4.metric(
    "Best F1-macro",
    f"{best_f1['f1_macro']:.4f}" if best_f1 is not None else "—",
    delta=f"±{best_f1['f1_macro_std']:.4f}" if best_f1 is not None else None,
)

st.markdown("---")

fig = plot_metrics_comparison(df_summary)
st.plotly_chart(fig, use_container_width=True)

st.markdown("---")
st.subheader("All Experiments")

cols = ["experiment", "model", "version", "accuracy", "balanced_accuracy", "f1_macro",
        "model_params", "duration_sec", "batch_size", "weight_decay", "lr_scheduler"]
display_cols = [c for c in cols if c in df_summary.columns]
df_display = df_summary[display_cols].copy()

for c in ["accuracy", "balanced_accuracy"]:
    if c in df_display.columns:
        df_display[c] = df_display[c].apply(lambda x: f"{x:.2%}" if pd.notna(x) else "—")
if "f1_macro" in df_display.columns:
    df_display["f1_macro"] = df_display["f1_macro"].apply(
        lambda x: f"{x:.4f}" if pd.notna(x) else "—"
    )

st.dataframe(
    df_display.sort_values("accuracy" if "accuracy" in df_display.columns else "experiment",
                           ascending=False),
    use_container_width=True,
    hide_index=True,
)

st.caption(f"Data from `outputs/models/{ds}/` — Generated by benchmark_modma.py")
